const main = async () => {
  console.log("hello");
};

main().catch((err) => console.error(err));
